//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCatalogueProduit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Categorie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cat_Categorie()
        {
            this.Cat_Produit = new HashSet<Cat_Produit>();
        }
    
        public int Code_Categorie { get; set; }
        public string Libelle_Categorie { get; set; }
        public Nullable<System.DateTime> Date_Saisie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cat_Produit> Cat_Produit { get; set; }
    }
}
