//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCatalogueProduit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Produit
    {
        public int Code_Produit { get; set; }
        public Nullable<int> Code_Categorie { get; set; }
        public string Libelle_Produit { get; set; }
        public string Description_Produit { get; set; }
        public string Image_Produit { get; set; }
        public string Url_Image_Produit { get; set; }
        public Nullable<System.DateTime> Date_Saisie { get; set; }
    
        public virtual Cat_Categorie Cat_Categorie { get; set; }
        public virtual Cat_Produit Cat_Produit1 { get; set; }
        public virtual Cat_Produit Cat_Produit2 { get; set; }
    }
}
