//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCatalogueProduit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Catalogue_Entities : DbContext
    {
        public Catalogue_Entities()
            : base("name=Catalogue_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           
        }
    
        public virtual DbSet<Cat_Categorie> Cat_Categorie { get; set; }
        public virtual DbSet<Cat_Produit> Cat_Produit { get; set; }
    }
}
